FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

# Production using nginx
FROM nginx:alpine

RUN mkdir -p /var/www/teddystack/dist

# Copy built files
COPY --from=builder /app/dist /var/www/teddystack/dist
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]